name: ClearView CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Backend
        working-directory: backend
        run: ./mvnw clean install -DskipTests=false

      - name: Run Unit Tests
        working-directory: backend
        run: ./mvnw test

      - name: Verify Build Artifact
        working-directory: backend
        run: ls -la target

      - name: CI Completed
        run: echo "ClearView backend build & test pipeline completed."
